#!/usr/bin/env python3
"""
Generate complete Rust version list for CC Version Guard
This script parses the user-provided version list and generates Rust ArchiveVersion structs
"""

# All versions provided by user, in chronological order (newest first)
VERSIONS = """
5.4.0 (Beta6)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1991_beta6_capcutpc_beta_creatortool.exe
5.4.0 (Beta5)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1988_beta5_capcutpc_beta_creatortool.exe
5.4.0 (Beta4)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1982_beta4_capcutpc_beta_creatortool.exe
5.4.0 (Beta3)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1979_beta3_capcutpc_beta_creatortool.exe
5.4.0 (Beta2)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1978_beta2_capcutpc_beta_creatortool.exe
5.4.0 (Beta1)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_4_0_1976_beta1_capcutpc_beta_creatortool.exe
5.3.0 (Latest)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1964_capcutpc_0_creatortool.exe
5.3.0 (Test2)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1961_capcutpc_0_creatortool.exe
5.3.0 (Test1)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1957_capcutpc_0_creatortool.exe
5.3.0 (Beta5)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1962_beta5_capcutpc_beta_creatortool.exe
5.3.0 (Beta4)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1956_beta4_capcutpc_beta_creatortool.exe
5.3.0 (Beta3)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1952_beta3_capcutpc_beta_creatortool.exe
5.3.0 (Latest) (Beta2)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1949_beta2_capcutpc_beta_creatortool.exe
5.3.0 (Test1) (Beta2)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1947_beta2_capcutpc_beta_creatortool.exe
5.3.0 (Latest) (Beta1)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1942_beta1_capcutpc_beta_creatortool.exe
5.3.0 (Test1) (Beta1)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_3_0_1941_beta1_capcutpc_beta_creatortool.exe
5.2.0 (Latest)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_2_0_1950_capcutpc_0_creatortool.exe
5.2.0 (Test3)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_2_0_1946_capcutpc_0_creatortool.exe
5.2.0 (Test2)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_2_0_1940_capcutpc_0_creatortool.exe
5.2.0 (Test1)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_2_0_1939_capcutpc_0_creatortool.exe
5.2.0 (Beta8)|https://lf16-capcut.faceulv.com/obj/capcutpc-packages-us/packages/CapCut_5_2_0_1945_beta8_capcutpc_beta_creatortool.exe
"""

def parse_version(line):
    """Parse a version line into (label, url)"""
    parts = line.strip().split('|')
    if len(parts) != 2:
        return None
    return parts[0].strip(), parts[1].strip()

def extract_base_version(label):
    """Extract base version number (e.g., '5.4.0' from '5.4.0 (Beta6)')"""
    import re
    match = re.match(r'(\d+\.\d+\.\d+)', label)
    return match.group(1) if match else "Unknown"

def determine_risk_level(label, base_version):
    """Determine risk level based on version"""
    major = int(base_version.split('.')[0])

    if major >= 5:
        return "High"
    elif major >= 4:
        return "High"
    elif major >= 3:
        return "Medium"
    else:
        return "Low"

def generate_rust_struct(label, url):
    """Generate a single ArchiveVersion Rust struct"""
    base_version = extract_base_version(label)
    risk_level = determine_risk_level(label, base_version)

    # Determine description
    if "Beta6" in label and "5.4.0" in label:
        desc = "Last version compatible with CC Version Guard"
    elif "Beta" in label or "Test" in label:
        desc = "Beta/Test release"
    elif "Latest" in label:
        desc = "Stable release"
    else:
        desc = "Release version"

    return f'''        ArchiveVersion {{
            persona: "{label}".to_string(),
            version: "{base_version}".to_string(),
            description: "{desc}".to_string(),
            features: vec![],
            download_url: "{url}".to_string(),
            risk_level: "{risk_level}".to_string(),
        }},'''

def main():
    print("// Generated by scripts/generate_all_versions.py")
    print("// DO NOT EDIT MANUALLY - regenerate using the script\n")

    lines = [l.strip() for l in VERSIONS.strip().split('\n') if l.strip() and '|' in l]

    for line in lines:
        parsed = parse_version(line)
        if parsed:
            label, url = parsed
            print(generate_rust_struct(label, url))

if __name__ == "__main__":
    main()
